### ISSUE TITLE
Missing methods?

### ISSUE THREAD

**Issue by ellisgl** [kerozene/cahbot#4]
These methods seem to be missing (definitely not in the irc package I know of):
client.nickHasChanMode
client.nickHasOp
client.who

**Comment by kerozene** [comment]
Hi!

Yes, this version is designed to run on [my fork of node-irc](https://github.com/kerozene/node-irc/tree/develop) as a locally linked module.

I just haven't updated the readme in forever.

**Comment by ellisgl** [comment]
Ah!

should update the package.json:
"irc": "git+https://github.com/kerozene/node-irc.git",

**Comment by ellisgl** [comment]
Now I see a couple of other missing methods:
in controllers\users.js bot.client.nickToUser doesn't exist.

**Comment by kerozene** [comment]
> should update the package.json

Cheers. That's a [better way indeed](https://github.com/kerozene/irc-cah/commit/d88a23c465863329cbb9e2ed551433cceb9390c1). Just to note: it's using the 'develop' branch of node-irc.

And yeah, there are a few other methods like that sprinkled around. We use WHOX replies to check the registered account on the network (also extended-join) and we also store every channel mode that a nick has (so we can devoice players even when they're opped, for example). I don't find the original node-irc's limited hierarchical view of such modes to be very helpful but this is a backwards-incompatible change that likely wouldn't be accepted upstream.
