### ISSUE TITLE
Complete Fork?

### ISSUE THREAD

**Issue by ellisgl** [kerozene/cahbot#8]
Since there have been so many changes, why not completely fork it to it's own project instead of being a fork of teeli/irc-cah?

**Comment by ellisgl** [comment]
Any thoughts on this?

**Comment by kerozene** [comment]
I don't understand the difference. How would that work/benefit?

What I will start doing is pushing to a stable master branch and creating release tags. TBH I didn't think anyone else was using this. :)

**Comment by ellisgl** [comment]
Well I was thinking it would be worthy of a complete branch off, since you use a custom IRC dependency. I actually started one myself. I need to do docs, because I'm "borrowing" some of your code and need to give you credit (also some other people's stuff too).

**Comment by ellisgl** [comment]
So any thought of spinning it up separately?
